### ISSUE TITLE
Handling Reserved Keywords

### ISSUE THREAD

**Issue by kevinjbayer** [wvanbergen/scoped_search#137] opened 2015-10-13 18:43 UTC
In the query language section, I'm experiencing some of the unexpected behaviour it mentions. Using "and" in a query seems to operate normal, but "at" results in "Field 'fish' not recognized for searching!" with the example of 'fish at chips'.

'at' is used quite a bit in my results, so I'm trying to figure out how best to handle this. I like the query results of scoped_search better than when I used pg_search, but I might need to switch back if it can handle these results better. If anyone knows of a way around this, please let me know. I couldn't find any other issues or stackoverflow questions about it.

**Comment by wvanbergen** [comment] 2016-08-23 11:05
Sorry for the late response. I am having a hard time understanding exactly what the issue is you are referring to. Could you provide us with an example search definition + query string that exposes the problem?

**Comment by domcleal** [comment] 2016-08-23 11:19
I think the report is that a search for the string `fish at chips` is treating the word `at` as an operator (it's an alias to equals), then raising an error because `fish` isn't a field rather than doing a free text search.

If you quote the entire string, i.e. `"fish at chips"` then you'll get a free text search as intended. If not, it'll be field-based. `fish and chips` is only working because `and` is an operator, not that it's part of the phrase.

**Comment by kevinjbayer** [comment] 2016-08-23 14:48
Yeah, domcleal is correct as to the issue that was occurring. I switched back to pg_search a while back so had forgotten about this issue. Not sure if I can give you any other detail other than what's in the original issue since I'm no longer using the gem. Sorry.

**Comment by domcleal** [comment] 2016-08-26 10:29
Thanks for confirming. I think I'm going to close this as it appears to be working as intended - if you quote the whole string then it'd be treated as a free text search, otherwise it expects a "FIELD at VALUE" type syntax, hence the error received.

**Closed by domcleal** 2016-08-26 10:29 UTC
