### ISSUE TITLE
'Not equal to' on has_many_through

### ISSUE THREAD

**Issue by shlomizadok** [wvanbergen/scoped_search#98] opened 2014-09-18 11:03 UTC
This issue is related to [theforeman issue #7383](http://projects.theforeman.org/issues/7383)
When I search on 'relation !=' and I have two relations (which one is = and the other one is !=)it will return on the search results.
Example:
I have a user who belongs to two organizations (organization_id = 3 and organization_id = 4).
When I will search on users 'organization_id != 3' that user will return on the search result.

we thought a nice enhancement on scoped_search would be adding external method by operators:
```ruby
scoped_search :in => :organizations, :on => :id, :rename => :organization_id, :complete_value => true, :only_operator => '!=', :ext_method => :fix_it_method
scoped_search :in => :organizations, :on => :id, :rename => :organization_id, :complete_value => true
```
This way, I could build an external method only to that operator.

Do you have a way to ensure that it will not return on the search result?

Thanks,

**Comment by wvanbergen** [comment] 2015-08-02 10:33
Closing this as it is working as intended.

Feel free to add any ideas about improvements for `:ext_method` to #110

**Closed by wvanbergen** 2015-08-02 10:33 UTC
