### ISSUE TITLE
Using search in STI for both base and child class causes errors

### ISSUE THREAD

**Issue by orrabin** [wvanbergen/scoped_search#135] opened 2015-08-31 14:23 UTC
I defined a base class and a child class and used most of the scoped_search definitions in the base class since they where relevant for all children.
I have a `belongs_to` definition in the child (it's not mentioned in the parent) and I added:
` scoped_search :in => ASSOCIATION, :on => :name, :complete_value => true, :rename => name`
in the child.
Trying to search/order by the child's association resulted in the error:
undefined method `klass' for nil:NilClass

part of the stach trace:
scoped_search (3.2.2) lib/scoped_search/definition.rb:62:in `klass'
scoped_search (3.2.2) lib/scoped_search/query_builder.rb:299:in `to_sql'
scoped_search (3.2.2) lib/scoped_search/query_builder.rb:98:in `order_by'
scoped_search (3.2.2) lib/scoped_search/query_builder.rb:533:in `order_by'
scoped_search (3.2.2) lib/scoped_search/query_builder.rb:66:in `build_find_params'
scoped_search (3.2.2) lib/scoped_search/query_builder.rb:22:in `build_query'
scoped_search (3.2.2) lib/scoped_search/definition.rb:255:in `block in register_named_scope!'
activerecord (3.2.21) lib/active_record/scoping/named.rb:178:in `call'
activerecord (3.2.21) lib/active_record/scoping/named.rb:178:in `block (2 levels) in scope'
activerecord (3.2.21) lib/active_record/scoping/default.rb:41:in `block in unscoped'
activerecord (3.2.21) lib/active_record/relation.rb:241:in `block in scoping'
activerecord (3.2.21) lib/active_record/scoping.rb:98:in `with_scope'
activerecord (3.2.21) lib/active_record/relation.rb:241:in `scoping'
activerecord (3.2.21) lib/active_record/scoping/default.rb:41:in `unscoped'
activerecord (3.2.21) lib/active_record/scoping/named.rb:178:in `block in scope'
activerecord (3.2.21) lib/active_record/relation/delegation.rb:14:in `block in search_for'
activerecord (3.2.21) lib/active_record/relation.rb:241:in `block in scoping'
activerecord (3.2.21) lib/active_record/scoping.rb:98:in `with_scope'
activerecord (3.2.21) lib/active_record/relation.rb:241:in `scoping'
activerecord (3.2.21) lib/active_record/relation/delegation.rb:14:in `search_for'

**Comment by wvanbergen** [comment] 2015-08-31 14:25
Duplicate of #112.

**Closed by wvanbergen** 2015-08-31 14:25 UTC
